export const MESSAGE = {
  PROJECT_NAME_REQUIRED: "PROJECT NAME REQUIRED",
  PROJECT_CUSTOMER_REQUIRED: "PROJECT CUSTOMER REQUIRED",
  PROJECT_TYPE_INVALID: "PROJECT TYPE INVALID",
  PROJECT_START_DATE_REQUIRED: "PROJECT START DATE REQUIRED",
  PROJECT_END_DATE_INVALID: "PROJECT END DATE GREATHER THAN OR EQUAL START DATE",
  PROJECT_DESCRIPTION_REQUIRED: "PROJECT DESCRIPTION REQUIRED",
  PROJECT_TECH_REQUIRED: "PROJECT TECH REQUIRED",
}